# Global agent-config command projection for GNU Make.
# This file is auto-discovered before Makefile and leaves the project file intact.
# <!-- Generated by agent-config; edit the canonical source. -->

_AGENT_CONFIG_PROJECT_ROOT := $(abspath $(dir $(firstword $(MAKEFILE_LIST))))
ifneq ($(wildcard $(_AGENT_CONFIG_PROJECT_ROOT)/Makefile),)
include $(_AGENT_CONFIG_PROJECT_ROOT)/Makefile
else ifneq ($(wildcard $(_AGENT_CONFIG_PROJECT_ROOT)/makefile),)
include $(_AGENT_CONFIG_PROJECT_ROOT)/makefile
else
.PHONY: help
.DEFAULT_GOAL := help
help:
	@printf '%s\n' 'No project Makefile; global targets available: make ready-task / make finish-task'
ifneq ($(wildcard $(_AGENT_CONFIG_PROJECT_ROOT)/package.json),)
.PHONY: validate
validate:
	@npm run validate
endif
endif

.PHONY: finish-task ready-task
finish-task:
	@"$(_AGENT_CONFIG_PROJECT_ROOT)/scripts/finish-task.sh" $(ARGS)

ready-task:
	@"$(_AGENT_CONFIG_PROJECT_ROOT)/scripts/ready-task.sh" $(ARGS)
