#!/usr/bin/env bash
# Project shim: forwards to the canonical agent-config cleanup helper.
# <!-- Generated by agent-config; edit the canonical source. -->
set -euo pipefail

root="${AGENT_CONFIG_HOME:-$HOME/.agents}"
canonical="$root/scripts/cleanup-merged-worktrees.sh"
[[ -x $canonical || -f $canonical ]] || {
  printf 'error: missing canonical cleanup script: %s\n' "$canonical" >&2
  exit 1
}
exec bash "$canonical" "$@"
