#!/usr/bin/env bash
# Project shim: forwards to the canonical agent-config finish-task command.
# <!-- Generated by agent-config; edit the canonical source. -->
set -euo pipefail

root="${AGENT_CONFIG_HOME:-$HOME/.agents}"
canonical="$root/scripts/finish-task.sh"
[[ -x $canonical || -f $canonical ]] || {
  printf 'error: missing canonical finish-task script: %s\n' "$canonical" >&2
  exit 1
}
exec bash "$canonical" "$@"
